Repository Nexters/PomoNyang-fe, pull requests merged in 2024-10, with the labels that each got.

#55 ci: 버전 업 관련 아무것도 없으면 스킵 처리
  .github/workflows/bump-up.yml
Labels: 🌎 Deploy

#56 fix: 시간 계산하는 로직 일부 수정
  src/renderer/entities/pomodoro/types.ts
  src/renderer/features/pomodoro/hooks/use-pomodoro.ts
  src/renderer/pages/pomodoro.tsx
  src/renderer/shared/ui/dialog.tsx
Labels: 👻 Fix

#57 feat: 개발시 초과시간까지 빠르게 테스트하기 위한 처리 추가
  src/renderer/pages/pomodoro.tsx
Labels: ⚙️ Setting

#58 fix: 고양이 클릭시 메세지가 랜덤으로 나오도록 수정
  src/renderer/widgets/pomodoro/ui/home-screen.tsx
Labels: 🐞 Bug
