Repository Nexters/PomoNyang-fe, pull requests merged in 2024-08, with the labels that each got.

#21 feat: 디자인 시스템 추가 (버튼, select, 타이포, 토글)
  package.json
  src/renderer/app/index.css
  src/renderer/pages/home.tsx
  src/renderer/shared/ui/button.tsx
  src/renderer/shared/ui/drawer.tsx
  src/renderer/shared/ui/index.ts
  src/renderer/shared/ui/select.tsx
  src/renderer/shared/ui/toast.tsx
  src/renderer/shared/ui/toggle-group.tsx
  src/renderer/shared/ui/toggle.tsx
  tailwind.config.js
  yarn.lock
Labels: ✨ Feature

#20 feat: 아이콘, 토스트, 툴팁 컴포넌트 추가
  package.json
  src/renderer/pages/home.tsx
  src/renderer/pages/pomodoro.tsx
  src/renderer/shared/assets/svgs/placeholder.svg
  src/renderer/shared/ui/icon.tsx
  src/renderer/shared/ui/index.ts
  src/renderer/shared/ui/toast.tsx
  src/renderer/shared/ui/toaster.tsx
  src/renderer/shared/ui/tooltip.tsx
  src/renderer/shared/ui/use-toast.ts
  yarn.lock
Labels: ✨ Feature

#22 feat: 온보딩 페이지 ui 구현
  src/renderer/pages/onboarding.tsx
  src/renderer/shared/ui/carousel.tsx
Labels: ✨ Feature

#18 feat: 토큰 발급 및 재발급 로직 추가
  src/main/main.ts
  src/renderer/entities/cat/index.ts
  src/renderer/entities/cat/types.ts
  src/renderer/entities/user/index.ts
  src/renderer/entities/user/types.ts
  src/renderer/features/auth/hooks/use-user.ts
  src/renderer/features/auth/index.ts
  src/renderer/pages/home.tsx
  src/renderer/shared/api/httpClient.ts
  src/renderer/shared/hooks/index.ts
  src/renderer/shared/hooks/use-auth-client.ts
  src/renderer/shared/hooks/use-auth-token.ts
  src/renderer/shared/utils/index.ts
  src/renderer/shared/utils/storage.ts
  src/renderer/vite-env.d.ts
  vite.main.config.ts
Labels: ✨ Feature, ⚙️ Setting

#23 feat: 고양이 선택 페이지 ui 구현
  src/renderer/pages/selection.tsx
  src/renderer/shared/ui/icon.tsx
  src/renderer/shared/ui/toaster.tsx
Labels: ✨ Feature

#24 feat: 온보딩 페이지 일부 스타일 수정
  src/renderer/pages/onboarding.tsx
  tailwind.config.js
Labels: 🎨 Style

#25 feat: 첫 진입시 보여지는 가이드 페이지 구현
  package.json
  src/renderer/pages/pomodoro.tsx
  src/renderer/shared/ui/guide.tsx
  src/renderer/shared/ui/index.ts
  tailwind.config.js
  yarn.lock
Labels: ✨ Feature

#26 feat: 고양이 이름짓기 페이지 ui 구현
  src/renderer/app/router.tsx
  src/renderer/pages/home.tsx
  src/renderer/pages/naming.tsx
  src/renderer/pages/selection.tsx
  src/renderer/shared/assets/svgs/back.svg
  src/renderer/shared/constants/path.ts
  src/renderer/shared/ui/frame.tsx
  src/renderer/shared/ui/icon.tsx
  src/renderer/shared/ui/index.ts
  src/renderer/shared/ui/tooltip.tsx
Labels: 🎨 Style

#27 feat: 카테고리 변경 bottomSheet 구현
  src/renderer/app/index.css
  src/renderer/app/layout.tsx
  src/renderer/entities/cat/types.ts
  src/renderer/entities/category/index.ts
  src/renderer/entities/category/types.ts
  src/renderer/features/category/hooks/use-categories.ts
  src/renderer/features/category/index.ts
  src/renderer/features/user/hooks/use-user.ts
  src/renderer/features/user/index.ts
  src/renderer/pages/home.tsx
  src/renderer/pages/pomodoro.tsx
  src/renderer/shared/assets/svgs/category-default.svg
  src/renderer/shared/assets/svgs/category-exercise.svg
  src/renderer/shared/assets/svgs/category-study.svg
  src/renderer/shared/assets/svgs/category-work.svg
  src/renderer/shared/assets/svgs/close.svg
  src/renderer/shared/assets/svgs/menu.svg
  src/renderer/shared/assets/svgs/play.svg
  src/renderer/shared/ui/guide.tsx
  src/renderer/shared/ui/icon.tsx
  src/renderer/shared/utils/index.ts
  src/renderer/shared/utils/parse-iso-duration.ts
Labels: ✨ Feature, 🎨 Style

#28 feat: 시간변경 ui 구현
  src/renderer/features/time/index.ts
  src/renderer/features/time/ui/chage-time-dialog.tsx
  src/renderer/pages/pomodoro.tsx
  src/renderer/shared/assets/svgs/check.svg
  src/renderer/shared/assets/svgs/focus-time.svg
  src/renderer/shared/assets/svgs/minus.svg
  src/renderer/shared/assets/svgs/plus.svg
  src/renderer/shared/assets/svgs/rest-time.svg
  src/renderer/shared/constants/index.ts
  src/renderer/shared/constants/time.ts
  src/renderer/shared/hooks/index.ts
  src/renderer/shared/hooks/use-disclosure.ts
  src/renderer/shared/ui/button.tsx
  src/renderer/shared/ui/dialog.tsx
  src/renderer/shared/ui/icon.tsx
  src/renderer/shared/ui/index.ts
  src/renderer/shared/utils/icon.ts
  src/renderer/shared/utils/index.ts
  src/renderer/shared/utils/string.ts
Labels: ✨ Feature, 🎨 Style

#29 feat: 카테고리 시간 변경 api 연동
  src/renderer/entities/cat/types.ts
  src/renderer/features/category/hooks/use-update-category.ts
  src/renderer/features/category/index.ts
  src/renderer/features/category/ui/change-category-drawer.tsx
  src/renderer/features/time/ui/chage-time-dialog.tsx
  src/renderer/pages/pomodoro.tsx
  src/renderer/shared/api/httpClient.ts
  src/renderer/shared/assets/svgs/category-book.svg
  src/renderer/shared/assets/svgs/category-default.svg
  src/renderer/shared/assets/svgs/category-exercise.svg
  src/renderer/shared/assets/svgs/category-study.svg
  src/renderer/shared/assets/svgs/category-work.svg
  src/renderer/shared/assets/svgs/focus-time.svg
  src/renderer/shared/assets/svgs/play.svg
  src/renderer/shared/assets/svgs/rest-time.svg
  src/renderer/shared/ui/icon.tsx
  src/renderer/shared/utils/create-iso-duration.ts
  src/renderer/shared/utils/icon.ts
  src/renderer/shared/utils/index.ts
  src/renderer/shared/utils/parse-iso-duration.ts
Labels: ✨ Feature

#30 feat: 마이페이지 ui 구현 및 기능적용
  src/main/main.ts
  src/renderer/app/router.tsx
  src/renderer/features/time/hooks/use-focus-notification.ts
  src/renderer/features/time/index.ts
  src/renderer/pages/home.tsx
  src/renderer/pages/mypage.tsx
  src/renderer/pages/pomodoro.tsx
  src/renderer/shared/assets/svgs/chevron-right.svg
  src/renderer/shared/assets/svgs/offline-stat.svg
  src/renderer/shared/constants/path.ts
  src/renderer/shared/ui/icon.tsx
  src/renderer/shared/ui/toggle.tsx
Labels: ✨ Feature, 🎨 Style

#33 feat: 뽀모도로 시작 페이지
  src/renderer/entities/pomodoro/index.ts
  src/renderer/entities/pomodoro/types.ts
  src/renderer/features/pomodoro/hooks/use-add-pomodoro.ts
  src/renderer/features/pomodoro/index.ts
  src/renderer/features/pomodoro/util/cat-name-map.ts
  src/renderer/features/time/index.ts
  src/renderer/features/time/ui/time.tsx
  src/renderer/pages/pomodoro.tsx
  src/renderer/shared/hooks/use-timer.ts
  src/renderer/shared/utils/index.ts
  src/renderer/shared/utils/time.ts
  src/renderer/widgets/pomodoro/index.ts
  src/renderer/widgets/pomodoro/ui/focus-screen.tsx
  src/renderer/widgets/pomodoro/ui/home-screen.tsx
  src/renderer/widgets/pomodoro/ui/rest-screen.tsx
  src/renderer/widgets/pomodoro/ui/rest-wait-screen.tsx
Labels: ✨ Feature

#32 feat: 나의 고양이 페이지 ui 및 기능 구현
  src/renderer/app/router.tsx
  src/renderer/pages/mycat.tsx
  src/renderer/pages/mypage.tsx
  src/renderer/pages/naming.tsx
  src/renderer/pages/selection.tsx
  src/renderer/shared/assets/svgs/pen.svg
  src/renderer/shared/constants/path.ts
  src/renderer/shared/ui/icon.tsx
Labels: ✨ Feature, 🎨 Style

#34 feat: 집중 페이지 수정 (handleReset, handleEnd, 툴팁메세지)
  src/renderer/pages/pomodoro.tsx
  src/renderer/shared/utils/time.ts
  src/renderer/widgets/pomodoro/ui/focus-screen.tsx
Labels: ✨ Feature

#35 feat: 휴식 페이지 ui 및 로직 일부 구현
  package.json
  src/renderer/entities/pomodoro/types.ts
  src/renderer/pages/pomodoro.tsx
  src/renderer/shared/ui/icon.tsx
  src/renderer/vite-env.d.ts
  src/renderer/widgets/pomodoro/ui/rest-screen.tsx
  vite.renderer.config.ts
  yarn.lock
Labels: ✨ Feature, 🎨 Style

#36 feat: (당장은) 불필요한 코드들 제거 & 쿼리키 한곳으로 이동
  src/renderer/app/provider.tsx
  src/renderer/app/router.tsx
  src/renderer/entities/pomodoro/api.ts
  src/renderer/entities/pomodoro/hooks/queries.ts
  src/renderer/features/cat/hooks/use-cats.ts
  src/renderer/features/cat/hooks/use-rename-selected-cat.ts
  src/renderer/features/cat/hooks/use-select-cat.ts
  src/renderer/features/category/hooks/use-categories.ts
  src/renderer/features/category/hooks/use-update-category.ts
  src/renderer/features/update-pomodoro/hooks/usePomodoroMutation.ts
  src/renderer/features/update-pomodoro/index.ts
  src/renderer/features/update-pomodoro/ui/button.tsx
  src/renderer/features/user/hooks/use-user.ts
  src/renderer/pages/home.tsx
  src/renderer/pages/second.tsx
  src/renderer/shared/constants/index.ts
  src/renderer/shared/constants/keys.ts
  src/renderer/shared/constants/path.ts
  src/renderer/shared/hooks/index.ts
  src/renderer/shared/hooks/use-auth-token.ts
  src/renderer/shared/hooks/use-machine-id.ts
  src/renderer/shared/utils/create-persister.ts
Labels: 🔨 Refactor

#37 feat: 휴식 대기 페이지 추가
  src/renderer/features/category/index.ts
  src/renderer/features/category/ui/category-chip.tsx
  src/renderer/pages/pomodoro.tsx
  src/renderer/shared/hooks/use-timer.ts
  src/renderer/widgets/pomodoro/ui/rest-screen.tsx
  src/renderer/widgets/pomodoro/ui/rest-wait-screen.tsx
Labels: ✨ Feature

#38 feat: 유저 flow 적용 및 기타
  src/renderer/app/router.tsx
  src/renderer/features/time/hooks/use-focus-notification.ts
  src/renderer/pages/home.tsx
  src/renderer/pages/mypage.tsx
  src/renderer/pages/onboarding.tsx
  src/renderer/shared/constants/keys.ts
  src/renderer/widgets/pomodoro/ui/home-screen.tsx
Labels: ✨ Feature

#39 feat: 전체 뽀모도로 플로우 적용 & 뽀모도로 알람 토스트
  src/renderer/entities/pomodoro/index.ts
  src/renderer/pages/pomodoro.tsx
  src/renderer/shared/constants/keys.ts
  src/renderer/shared/hooks/use-timer.ts
  src/renderer/shared/utils/time.ts
  src/renderer/widgets/pomodoro/ui/home-screen.tsx
  src/renderer/widgets/pomodoro/ui/rest-wait-screen.tsx
Labels: ✨ Feature

#40 feat: 집중시간/휴식시간 +-5 반영
  src/renderer/entities/pomodoro/types.ts
  src/renderer/pages/pomodoro.tsx
Labels: ✨ Feature

#41 feat: 휴식 대기 페이지에 로티 추가
  package.json
  src/renderer/shared/assets/lotties/loti_complete_focus.json
  src/renderer/shared/assets/lotties/loti_particle.json
  src/renderer/widgets/pomodoro/ui/rest-screen.tsx
  src/renderer/widgets/pomodoro/ui/rest-wait-screen.tsx
  yarn.lock
Labels: ✨ Feature

#42 feat: rive 적용하기
  src/renderer/pages/mycat.tsx
  src/renderer/pages/naming.tsx
  src/renderer/pages/selection.tsx
  src/renderer/shared/assets/rivs/cat_focus.riv
  src/renderer/shared/assets/rivs/cat_home.riv
  src/renderer/shared/assets/rivs/cat_rest.riv
  src/renderer/shared/assets/rivs/cat_select_ver2.0.riv
  src/renderer/shared/hooks/index.ts
  src/renderer/shared/hooks/use-rive-cat.ts
  src/renderer/widgets/pomodoro/ui/focus-screen.tsx
  src/renderer/widgets/pomodoro/ui/home-screen.tsx
  src/renderer/widgets/pomodoro/ui/rest-screen.tsx
Labels: ✨ Feature

#43 feat: 이미지 및 아이콘 적용
  package.json
  src/renderer/pages/home.tsx
  src/renderer/pages/onboarding.tsx
  src/renderer/pages/selection.tsx
  src/renderer/shared/assets/images/app-icon.png
  src/renderer/shared/assets/images/onboarding-1.png
  src/renderer/shared/assets/images/onboarding-2.png
  src/renderer/shared/assets/images/onboarding-3.png
  src/renderer/shared/assets/svgs/app-symbol.svg
  src/renderer/shared/assets/svgs/clock.svg
  src/renderer/shared/ui/icon.tsx
  src/renderer/shared/ui/toast.tsx
  src/renderer/shared/ui/toaster.tsx
  yarn.lock
Labels: ✨ Feature

#45 feat: 배포 직전 챙길만한거 챙겨보기
  forge.config.ts
  package.json
  src/main/main.ts
  src/preload/preload.ts
  src/renderer/pages/home.tsx
  src/renderer/pages/mycat.tsx
  src/renderer/pages/naming.tsx
  src/renderer/pages/onboarding.tsx
  src/renderer/pages/selection.tsx
  src/renderer/shared/hooks/use-auth-token.ts
  src/renderer/shared/hooks/use-notification.ts
  src/renderer/widgets/pomodoro/ui/focus-screen.tsx
  src/renderer/widgets/pomodoro/ui/home-screen.tsx
  src/renderer/widgets/pomodoro/ui/rest-screen.tsx
  src/shared/assets/icons/icon.icns
  src/shared/assets/icons/icon.ico
  src/shared/assets/icons/icon.png
  src/shared/assets/icons/icon@2x.icns
  src/shared/assets/icons/icon@2x.png
  src/shared/type.ts
Labels: ✨ Feature, ⚙️ Setting

#46 feat: github action을 활용한 release 준비
  .github/workflows/release.yml
  add-osx-cert.sh
  forge.config.ts
  package.json
  src/main/main.ts
  yarn.lock
Labels: 🌎 Deploy, ⚙️ Setting

#47 fix: 이것저것 수정
  src/renderer/pages/mypage.tsx
  src/renderer/pages/naming.tsx
  src/renderer/pages/onboarding.tsx
  src/renderer/shared/assets/svgs/ready-for-stat.svg
  src/renderer/shared/ui/icon.tsx
  src/renderer/shared/ui/toaster.tsx
  src/renderer/shared/ui/use-toast.ts
  src/renderer/widgets/pomodoro/ui/focus-screen.tsx
  src/renderer/widgets/pomodoro/ui/home-screen.tsx
Labels: 👻 Fix

#49 feat: tailwind sort prettier plugin 적용
  .prettierrc
  package.json
  src/renderer/app/layout.tsx
  src/renderer/features/category/ui/category-chip.tsx
  src/renderer/features/category/ui/change-category-drawer.tsx
  src/renderer/features/pomodoro/ui/timeout-dialog.tsx
  src/renderer/features/time/ui/chage-time-dialog.tsx
  src/renderer/pages/home.tsx
  src/renderer/pages/mycat.tsx
  src/renderer/pages/mypage.tsx
  src/renderer/pages/naming.tsx
  src/renderer/pages/onboarding.tsx
  src/renderer/pages/selection.tsx
  src/renderer/shared/ui/carousel.tsx
  src/renderer/shared/ui/dialog.tsx
  src/renderer/shared/ui/frame.tsx
  src/renderer/shared/ui/guide.tsx
  src/renderer/shared/ui/toast.tsx
  src/renderer/shared/ui/toggle.tsx
  src/renderer/shared/ui/tooltip.tsx
  src/renderer/widgets/pomodoro/ui/focus-screen.tsx
  src/renderer/widgets/pomodoro/ui/home-screen.tsx
  src/renderer/widgets/pomodoro/ui/rest-screen.tsx
  src/renderer/widgets/pomodoro/ui/rest-wait-screen.tsx
  yarn.lock
Labels: 🎨 Style

#51 feat: main 브랜치 머지할때 자동 tagging
  .github/workflows/bump-up.yml
  .github/workflows/release.yml
  src/renderer/pages/onboarding.tsx
Labels: ⚙️ Setting

#52 fix: 타이머 정상적으로 돌아가도록 수정
  src/renderer/shared/hooks/use-timer.ts
Labels: 👻 Fix
