Repository Nexters/PomoNyang-fe, pull requests merged in 2024-07, with the labels that each got.

#2 feat: 초기 세팅 & prettier & eslint
  .eslintrc.json
  .github/CODEOWNERS
  .github/pull_request_template.md
  .prettierrc
  components.json
  forge.config.ts
  forge.env.d.ts
  index.html
  package.json
  postcss.config.js
  src/main/main.ts
  src/preload/preload.ts
  src/renderer/app.tsx
  src/renderer/components/ui/button.tsx
  src/renderer/index.css
  src/renderer/pages/home.tsx
  src/renderer/renderer.ts
  src/renderer/utils.ts
  tailwind.config.js
  tsconfig.json
  vite.base.config.ts
  vite.main.config.ts
  vite.preload.config.ts
  vite.renderer.config.ts
  yarn.lock
Labels: ⚙️ Setting

#5 feat: 온보딩 페이지 구현을 위한 준비
  .gitignore
  .tool-versions
  package.json
  src/renderer/app/index.tsx
  src/renderer/app/router.tsx
  src/renderer/pages/home.tsx
  src/renderer/pages/onboarding.tsx
  src/renderer/shared/lib/constants/path.ts
  src/renderer/shared/ui/carousel.tsx
  tsconfig.json
  vite.base.config.ts
  yarn.lock
Labels: ✨ Feature

#9 fix: electron 는 파일기반이라 hash router 변경
  src/renderer/app/router.tsx
Labels: ⚙️ Setting

#8 feat: rive 라이브러리 적용해보기
  package.json
  src/renderer/app/router.tsx
  src/renderer/pages/home.tsx
  src/renderer/pages/selection.tsx
  src/renderer/shared/assets/rivs/skills.riv
  src/renderer/shared/hooks/index.ts
  src/renderer/shared/hooks/rive.ts
  src/renderer/shared/lib/constants/path.ts
  src/renderer/vite-env.d.ts
  vite.renderer.config.ts
  yarn.lock
Labels: ⚙️ Setting

#7 feat: offline first 대응 with react-query
  package.json
  src/renderer/app/provider.tsx
  src/renderer/app/router.tsx
  src/renderer/entities/pomodoro/api.ts
  src/renderer/entities/pomodoro/hooks/queries.ts
  src/renderer/entities/pomodoro/index.ts
  src/renderer/features/update-pomodoro/hooks/usePomodoroMutation.ts
  src/renderer/features/update-pomodoro/index.ts
  src/renderer/features/update-pomodoro/ui/button.tsx
  src/renderer/pages/home.tsx
  src/renderer/pages/onboarding.tsx
  src/renderer/pages/second.tsx
  src/renderer/shared/api/httpClient.ts
  src/renderer/shared/api/index.ts
  src/renderer/shared/constants/index.ts
  src/renderer/shared/constants/path.ts
  src/renderer/shared/ui/index.ts
  src/renderer/shared/utils/index.ts
  src/renderer/shared/utils/url.ts
  yarn.lock
Labels: ✨ Feature, ⚙️ Setting

#10 feat: desktop machine id 확인 및 표시 추가
  package.json
  src/main/main.ts
  src/preload/preload.ts
  src/renderer/pages/home.tsx
  src/renderer/shared/hooks/index.ts
  src/renderer/shared/hooks/machine-id.ts
  src/renderer/vite-env.d.ts
  src/shared/type.ts
  yarn.lock
Labels: ✨ Feature, ⚙️ Setting

#12 fix: src shared type 파일은 전역에서 import 없이 사용할 수 있도록
  src/renderer/vite-env.d.ts
Labels: 🐞 Bug, ⚙️ Setting

#11 feat: 타이머 훅 구현
  src/renderer/app/router.tsx
  src/renderer/features/update-pomodoro/index.ts
  src/renderer/pages/home.tsx
  src/renderer/pages/pomodoro.tsx
  src/renderer/pages/second.tsx
  src/renderer/shared/constants/path.ts
  src/renderer/shared/hooks/index.ts
  src/renderer/shared/hooks/use-timer.ts
Labels: ✨ Feature

#13 feat: .env 파일 지원하기
  .eslintrc.json
  src/renderer/global.d.ts
  src/renderer/pages/home.tsx
  src/renderer/shared/hooks/rive.ts
  src/renderer/tsconfig.json
  src/renderer/vite-env.d.ts
  tsconfig.json
Labels: ⚙️ Setting

#14 feat: 오프라인 -> 온라인일때 쌓인 요청 한번에 보내는것 확인
  src/renderer/app/provider.tsx
  src/renderer/features/update-pomodoro/hooks/usePomodoroMutation.ts
Labels: ✨ Feature

#15 feat: drawer (+ toast) 컴포넌트 추가
  package.json
  src/renderer/app/provider.tsx
  src/renderer/pages/pomodoro.tsx
  src/renderer/shared/ui/carousel.tsx
  src/renderer/shared/ui/drawer.tsx
  src/renderer/shared/ui/index.ts
  src/renderer/shared/ui/toast.tsx
  src/renderer/shared/ui/toaster.tsx
  src/renderer/shared/ui/use-toast.ts
  yarn.lock
Labels: ⚙️ Setting

#19 feat: spacing, color, borderRadius 토큰 추가
  tailwind.config.js
Labels: 🎨 Style
